name: astronauthelper
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  firebase_auth: ^0.16.1
  modal_progress_hud: ^0.1.3
  cloud_firestore: ^0.13.7
  shared_preferences: ^0.5.8
  provider: ^4.0.1
  flutter_datetime_picker: ^1.4.0
  flutter_local_notifications: ^1.4.4+5
  url_launcher: ^5.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:

  uses-material-design: true


  assets:
    - images/
    - images/general_information/

  fonts:
    - family: SansitaSwashed
      fonts:
        - asset: fonts/SansitaSwashed-Bold.ttf

